---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    device: dev0
    type: external
  name: dev0
  namespace: rpi-sensors
spec:
  endpoints:
    - interval: 1m
      port: metrics
  jobLabel: dev0
  namespaceSelector:
    matchNames:
      - rpi-sensors
  selector:
    matchLabels:
      device: dev0
      type: external
