---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    device: dev1
    type: external
  name: dev1
  namespace: rpi-sensors
spec:
  endpoints:
    - interval: 1m
      port: metrics
  jobLabel: dev1
  namespaceSelector:
    matchNames:
      - rpi-sensors
  selector:
    matchLabels:
      device: dev1
      type: external
