{
 "title": "RPI Sensors",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "RPI",
    "label": "RPI",
    "query": {
     "query": "label_values(sensor_exporter_info, job)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "rain_drops" }
   ]
  },
  {
   "title": "Rain Duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg_over_time(rain_drops[$__range])) * $__range_s/60"
    }
   ]
  },
  {
   "title": "UV Index",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "uv_index" }
   ]
  },
  {
   "title": "Sensors Overview - $RPI",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "repeat": "RPI",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sensor_exporter_info{job=\"$RPI\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Temperature - $RPI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "repeat": "RPI",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "temperature_celsius{job=\"$RPI\"}",
     "legendFormat": "{{sensor}} "
    }
   ]
  },
  { "title": "Air Humidity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Air Humidity - $RPI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "repeat": "RPI",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "air_humidity_percent{job=\"$RPI\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  { "title": "Pressure", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Pressure - $RPI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "repeat": "RPI",
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "expr": "pressure_pascals{job=\"$RPI\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  { "title": "Air Quality", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Gas Resistance - $RPI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "repeat": "RPI",
   "fieldConfig": { "defaults": { "unit": "ohm" } },
   "targets": [
    {
     "expr": "gas_resistance_ohms{job=\"$RPI\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  { "title": "Altitude", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Altitude - $RPI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "repeat": "RPI",
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "expr": "altitude_meters{job=\"$RPI\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  { "title": "Soil Moisture", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Soil Moisture - $RPI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "repeat": "RPI",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "soil_moisture_percent{job=\"$RPI\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  { "title": "Light Intencity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Visible Light Intensity - $RPI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "repeat": "RPI",
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "expr": "visible_light_intensity_lux{job=\"$RPI\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  },
  {
   "title": "IR Light Intensity - $RPI",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "repeat": "RPI",
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "targets": [
    {
     "expr": "ir_light_intensity_lux{job=\"$RPI\"}",
     "legendFormat": "{{sensor}}"
    }
   ]
  }
 ]
}